server:
  port: 8081
  
logging:  level:    root: INFO
    org.springframework.web: INFO
    com.example: DEBUG
    org.hibernate: INFO
        
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/unicorns?useSSL=false&serverTimezone=UTC
    password: qwerty123!
    username:  root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    generate-ddl: true
    hibernate:      #ddl-auto: update
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect  sql:    init:      mode: ALWAYS
